### ISSUE TITLE
bytestring-0.12 not accepted

### ISSUE THREAD

**Issue by ysangkok** [GaloisInc/RSA#20]
This version of bytestring is shipped with GHC 9.8.

The constraint stems from the library and test-suite components:

https://github.com/GaloisInc/RSA/blob/28ab3195f86a0c7a4cd9dfe6737b0365e243515b/RSA.cabal#L24

**Comment by ysangkok** [comment]
@acw, even though it seems that you are no longer with Galois, it seems that you are [still the maintainer on Hackage](https://hackage.haskell.org/package/RSA/maintainers/). Would it be possible for you to make the Hackage revision that permits the new bytestring? It would be much appreciated.

**Comment by acw** [comment]
Hello! Yes, I'm no longer at Galois, so I'm a little uncomfortable mucking around with a repo under the Galois name. Also, it turns out, I don't have permission to do anything with it any more, which is probably all for the best. 😆

@jtdaugherty or @kquick, I don't suppose there's anyone at Galois that would want to take over maintenance of this library, perhaps justified as an indirect dependency of `matterhorn`? I'd be happy to update the Hackage access controls as appropriate.

**Comment by acw** [comment]
For reference, just updating the byte string constraint to `< 0.13` is fine; I validate that it works with `cargo test -c "bytestring>=0.12"`

**Comment by jtdaugherty** [comment]
@acw for now, please add me (`JonathanDaugherty`) as a Hackage maintainer and I'll get the version bounds updated. I'm following up internally about a longer-term maintainer. Also, Adam, you sure must be doing a lot of Rust to let that `cargo` command slip above. :-D

**Comment by acw** [comment]
Hah! Yes, I am. You should be good to go.

**Comment by kquick** [comment]
Please feel free to add me as well.

**Comment by jtdaugherty** [comment]
I've updated the metadata for RSA 2.4.1 with the above constraint change. Is that sufficient for your needs, @ysangkok?

**Comment by jtdaugherty** [comment]
While I was at it, I removed redundant test suite bounds that were duplicated from the library section.

**Comment by ysangkok** [comment]
Yes, that works. Thank you very much.
